### ISSUE TITLE
Make `NonZeroAble` sealed?

### ISSUE THREAD

**Issue by joshlf** [antifuchs/nonzero_ext#17]
We'd like to use `nonzero_ext` on Fuchsia, but in reviewing it, [a reviewer was concerned about the fact that `NonZeroAble` is not a sealed trait](https://fuchsia-review.googlesource.com/c/fuchsia/+/507379/1/third_party/rust_crates/vendor/nonzero_ext/src/lib.rs#232). Do you think it would make sense to make it a sealed trait in order to prevent misuse?

*In case you're not familiar, see [here](https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed) for an explanation of sealed traits.*

**Comment by antifuchs** [comment]
Hm, this is a good question! I thought to leave it open in order to allow other crates to implement `NonZeroAble` on their own types, e.g. for custom duration types and such. I'm not aware that anyone has done so yet, though.

Can you elaborate on the thing the reviewer was concerned about? (I'm not able to view this google-internal page.) Maybe that would make it easier to decide one way or another (:

**Comment by joshlf** [comment]
Oops, didn't intend for that to be Google-internal, sorry! I've edited the original comment with the correct link.

> I thought to leave it open in order to allow other crates to implement `NonZeroAble` on their own types, e.g. for custom duration types and such. I'm not aware that anyone has done so yet, though.

Another option that was discussed in the thread was making the `NonZeroAble` trait `unsafe` - that should preserve the ability of downstream crates to implement it for use cases like this.

**Comment by ComputerDruid** [comment]
The correct link is https://fuchsia-review.googlesource.com/c/fuchsia/+/507379/1/third_party/rust_crates/vendor/nonzero_ext/src/lib.rs#232 which you should be able to view without a login.

Also hi, I was the one who raised the question 👋. Happy to try to explain what I was thinking if that comment thread isn't clear

**Comment by antifuchs** [comment]
Aha! I see the objection now - if it's only centered on the macro, then I have good news for all of us: that one can't be tricked, because the type [`NonZeroLiteral<T>`](https://github.com/antifuchs/nonzero_ext/blob/456301e8c654dd929dc26ca5cad480779da3a6ec/src/literals.rs#L9) governs the ability to use constant expressions of type T in the macro (it's kinda a hack to allow the macro to return const exprs, but bear with me).

Due to the orphan rule, you can't impl `NonZeroLiteral<T>` outside the nonzero_ext crate, effectively restricting implementations of generic non-zeroability for the purposes of the macro as well as a sealed trait would.

Here's a test case that should illustrate:

``` rust
#[test]
fn adverse_conditions() {
    use std::num::NonZeroUsize;

    use nonzero_ext::nonzero;
    use nonzero_ext::{literals::NonZeroLiteral, NonZeroAble};

    struct BadInt(usize);
    impl BadInt {
        fn count_ones(&self) -> usize {
            1 // oops, even zero counts!
        }
    }
    impl NonZeroAble for BadInt {
        type NonZero = NonZeroUsize;

        fn into_nonzero(self) -> Option<Self::NonZero> {
            NonZeroUsize::new(self.0)
        }

        unsafe fn into_nonzero_unchecked(self) -> Self::NonZero {
            NonZeroUsize::new_unchecked(self.0)
        }
    }
    nonzero!(BadInt(0)); // This fails because we don't have an impl of NonZeroLiteral<BadInt>

    // And we can't impl:
    // impl NonZeroLiteral<BadInt> {} // <- also errors due to the orphan rule.
}
```

I guess I should add these to the compilefail test suite, so that a restructuring of the macro later won't accidentally open that road again.

**Comment by joshlf** [comment]
Ah, thanks for the clarification! @ComputerDruid , does this address your concern?

**Comment by ComputerDruid** [comment]
Thanks for the example! I'd totally missed that the macro is calling `NonNeroLiteral`'s `into_nonzero` instead of the one on `NonZeroAble`.

So technically you can trick the macro by implementing a `into_nonzero` for `NonZeroLiteral<BadInt>` via a trait:

```rust
#[test]
fn adverse_conditions() {
    use std::num::NonZeroUsize;

    use nonzero_ext::nonzero;
    use nonzero_ext::{literals::NonZeroLiteral, NonZeroAble};

    struct BadInt(usize);
    impl BadInt {
        const fn count_ones(&self) -> usize {
            1 // oops, even zero counts!
        }
    }
    impl NonZeroAble for BadInt {
        type NonZero = NonZeroUsize;

        fn into_nonzero(self) -> Option<Self::NonZero> {
            NonZeroUsize::new(self.0)
        }

        unsafe fn into_nonzero_unchecked(self) -> Self::NonZero {
            NonZeroUsize::new_unchecked(self.0)
        }
    }
    nonzero!(BadInt(0)); // This fails because we don't have an impl of NonZeroLiteral<BadInt>

    // While we can't impl:
    // impl NonZeroLiteral<BadInt> {} // <- also errors due to the orphan rule.
    // We can impl it via a trait:
    trait OtherTrait {
        /// # Safety
        /// self must not be NonZeroLiteral(BadInt(0))
        unsafe fn into_nonzero(self) -> NonZeroUsize;
    }
    
    impl OtherTrait for NonZeroLiteral<BadInt> {
        unsafe fn into_nonzero(self) -> NonZeroUsize {
            unsafe {
                self.0.into_nonzero_unchecked()
            }
        }
    }
}
```

That's admittedly a lot less scary, since you had to write an unsafe function and go out of your way to try to make it work on NonZeroLiteral. I think it is hypothetically a valid concern, though. When I define an unsafe function, I'm the one who declares what the safety requirements are for calling it, and the macro obviously isn't in a position to decide whether it's upholding them.

I haven't quite figured out what the ideal fix would be though. It does seem like the problem isn't actually with `NonZeroAble` at all, but rather the construction of the `NonZeroLiteral`.

**Comment by antifuchs** [comment]
Oh man, that's a really pretty gnarly problem with the way the macro expands... and I thought I was being clever with type inference and associated functions, there. Turns out people trying to trick your macro can be clever, too.

The solution here is quite clear: We make a sealed trait that is implemented by everything encapsulated in the `NonZeroLiteral`. That should ensure the `nonzero!` macro can only construct well-known literal types, and won't go awry with awkward user-defined ones.

**Comment by antifuchs** [comment]
I opened #18, I hope you can take a look & tell me what you think - hope this addresses the issue!
