### ISSUE TITLE
Make `as_nonzero_unchecked()` a const fn?

### ISSUE THREAD

**Issue by jbg** [antifuchs/nonzero_ext#5]
the `new_unchecked()` fn on the various NonZero types is a const fn, so I think if `as_nonzero_unchecked()` was as well, it would be possible to write things like:

```rust
const MY_NON_ZERO_U32: NonZeroU32 = nonzero!(42u32);
```

currently it gives the following compile error:

```
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
```

**Comment by antifuchs** [comment]
That's a marvelous idea! I'll take a stab at this today (:

**Comment by antifuchs** [comment]
...oh wait: Since the macro uses the `NonZeroAble` trait's associated method to convert the input, and associated functions can't be `const` (it's an [explicitly disallowed](https://doc.rust-lang.org/error-index.html#E0379)), that's not a viable path.

I'll try and see if we can find a different way!

**Comment by antifuchs** [comment]
OMG @jbg it took me more than a week, but I found a (hopefully acceptable) workaround. Please let me know what you think about #8 (:

**Comment by jbg** [comment]
Awesome. I like the solution, too! Thanks!
